-- Keep the database enums aligned with the closed application audit allowlists.
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'ADMIN_ROLE_ASSIGNMENT';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'ADMIN_CAPABILITY_GRANT';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'AUTHENTICATOR';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'SECURITY_CHALLENGE';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'SESSION_ASSURANCE';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'BREAK_GLASS_GRANT';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'RISK_SIGNAL';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'RISK_DECISION';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'TRUST_SAFETY_CASE';
ALTER TYPE "AuditTargetType" ADD VALUE IF NOT EXISTS 'TRUST_SAFETY_APPEAL';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ROLE_ASSIGNMENT_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ROLE_ASSIGNMENT_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_ROLE_ASSIGNMENT_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_CAPABILITY_GRANT_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_CAPABILITY_GRANT_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_CAPABILITY_GRANT_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTHENTICATOR_ENROLLMENT_STARTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTHENTICATOR_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTHENTICATOR_USED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AUTHENTICATOR_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECOVERY_CODES_ROTATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECOVERY_CODE_USED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_ASSURANCE_GRANTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SESSION_ASSURANCE_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_CHALLENGE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_GRANT_ISSUED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STEP_UP_GRANT_CONSUMED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BREAK_GLASS_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BREAK_GLASS_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BREAK_GLASS_REVOKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RISK_SIGNAL_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RISK_DECISION_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRUST_SAFETY_CASE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TRUST_SAFETY_APPEAL_CHANGED';

ALTER TABLE "AuthenticatorChallenge"
  ADD CONSTRAINT "AuthenticatorChallenge_authenticatorId_fkey"
  FOREIGN KEY ("authenticatorId") REFERENCES "Authenticator"("id")
  ON DELETE RESTRICT ON UPDATE CASCADE;
