-- Phase 26 splits company verification review from independent approval.
-- Existing general company-read access does not imply either mutation right.
CREATE OR REPLACE FUNCTION phase25_admin_capability_known(value TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT value = ANY (ARRAY[
    'ADMIN_OVERVIEW_READ','ADMIN_GLOBAL_SEARCH','ADMIN_JOB_REVIEW',
    'ADMIN_JOB_PUBLISH','ADMIN_JOB_BOOST_MANAGE','ADMIN_COMPANY_REVIEW',
    'COMPANY_VERIFICATION_REVIEW','COMPANY_VERIFICATION_APPROVE',
    'ADMIN_COMPANY_MODERATE','ADMIN_CLAIM_REVIEW','ADMIN_USER_MODERATE',
    'ADMIN_TAXONOMY_MANAGE','ADMIN_REPORT_REVIEW',
    'ADMIN_RESTRICTION_MANAGE','ADMIN_LICENSED_IMPORT',
    'ADMIN_IMPORT_SETUP_APPROVE','ADMIN_SUPPORT_MANAGE',
    'ADMIN_CONTENT_MANAGE','ADMIN_CLUSTER_PRODUCT_APPROVE',
    'ADMIN_CLUSTER_OPS_APPROVE','ADMIN_CLUSTER_ACTIVATE',
    'ADMIN_LEAD_MANAGE','ADMIN_COCKPIT_READ','ADMIN_OPS_READ',
    'ADMIN_AUDIT_READ','ADMIN_SYSTEM_TASK_MANAGE','ADMIN_BILLING_READ',
    'ADMIN_BILLING_MUTATE','ADMIN_CATALOG_READ','ADMIN_CATALOG_MUTATE',
    'ADMIN_INVOICE_MUTATE','ADMIN_ANALYTICS_READ','ADMIN_LEGAL_READ',
    'ADMIN_LEGAL_DRAFT','ADMIN_LEGAL_REVIEW','ADMIN_LEGAL_PUBLISH',
    'PRIVACY_EXECUTION_APPROVE','PRIVACY_HOLD_MANAGE',
    'ADMIN_CREDITS_GRANT','ADMIN_CREDIT_REVERSE','ADMIN_SLA_PROJECT',
    'PRIVACY_CASE_READ','PRIVACY_CASE_VERIFY','PRIVACY_CASE_PROCESS',
    'ADMIN_SECURITY_READ','ADMIN_SECURITY_GRANT','ADMIN_SECURITY_APPROVE',
    'ADMIN_AUTHENTICATOR_RESET','ADMIN_BREAK_GLASS_MANAGE',
    'TRUST_SAFETY_READ','TRUST_SAFETY_REVIEW','TRUST_SAFETY_RESTORE'
  ]::TEXT[]);
$$;

INSERT INTO "AdminRoleCapability" (
  "id",
  "adminRoleId",
  "capability",
  "createdAt"
)
SELECT
  gen_random_uuid(),
  role."id",
  mapping."capability",
  CURRENT_TIMESTAMP
FROM (
  VALUES
    ('TRUST_SAFETY_REVIEWER', 'COMPANY_VERIFICATION_REVIEW'),
    ('TRUST_SAFETY_APPROVER', 'COMPANY_VERIFICATION_APPROVE')
) AS mapping("roleCode", "capability")
JOIN "AdminRole" role ON role."code" = mapping."roleCode"
ON CONFLICT ("adminRoleId", "capability") DO NOTHING;
