ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_EVIDENCE';
ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_CHECK';
ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_DECISION';
ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_DOMAIN_CHALLENGE';
ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_APPEAL';
ALTER TYPE "AuditTargetType"
  ADD VALUE IF NOT EXISTS 'COMPANY_TRUST_PROJECTION';

ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_SUBMITTED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_CHECKED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_ASSIGNED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_DECIDED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_VERIFICATION_APPEALED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_TRUST_CHANGED_V2';
ALTER TYPE "AuditAction"
  ADD VALUE IF NOT EXISTS 'COMPANY_TRUST_EXPIRED_V2';
